apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: saga-k8s-prod

resources:
  - namespace.yaml
  - serviceaccount-default.yaml
  - ../../services/site-service
  - ../../services/uaa-service

configMapGenerator:
  - name: site-service-config
    literals:
      - SITE_SERVICES_UAA_URL=http://uaa-service:8080
      - SERVER_PORT=8080
      - LOG_LEVEL=INFO

secretGenerator:
  - name: dockerhub-creds
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=secrets/dockerconfigjson.prod.json

generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
