env:
  SPRING_PROFILES_ACTIVE: "mongo"
  JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75.0"
  LOG_LEVEL: "DEBUG"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
