replicaCount: 1

image:
  tag: 1.0.0

env:
  SITE_SERVICES_UAA_URL: "http://uaa-service:8080"
  LOG_LEVEL: "DEBUG"

ingress:
  host: site-service.saga-k8s.local

# Chemin Vault par environnement
vault:
  secretPath: secret/data/app/saga/dev/site-service
