replicaCount: 2

image:
  tag: "1.0.0"

env:
  SPRING_PROFILES_ACTIVE: "prod"
  VAULT_ADDR: "https://vault.prod.example.com"  # adapter selon ton Vault prod
  SITE_SERVICES_UAA_URL: "http://uaa-service:8080"
  LOG_LEVEL: "INFO"

ingress:
  host: site-service.saga.example.com

# Option B : pas de sidecar
vault:
  enabled: false

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi
